# Generated by Django 5.0.1 on 2024-01-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passengerID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('location1', models.CharField(max_length=255)),
                ('location2', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('IDstatus', models.BooleanField(choices=[(1, 'Valid'), (0, 'Invalid')], default=1)),
            ],
        ),
    ]
