# Generated by Django 5.0.1 on 2024-01-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='tap_count',
            field=models.IntegerField(default=0),
        ),
    ]
