# Generated by Django 5.0.1 on 2024-01-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_passenger_tap_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(max_length=255)),
                ('data', models.TextField()),
            ],
        ),
    ]
