# Generated by Django 5.0.1 on 2024-01-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_nfcdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusData',
            fields=[
                ('busID', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('totalEarned', models.IntegerField(default=0)),
                ('totalPassengers', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='passenger',
            name='Fare',
            field=models.IntegerField(default=0),
        ),
    ]
